// stubs/vue/components/SocialitePlus.vue
<script setup lang="ts">
import { Button } from "@/components/ui/button";
import FacebookIcon from "./Icons/FacebookIcon.vue";
import GitHubIcon from "./Icons/GitHubIcon.vue";
import GoogleIcon from "./Icons/GoogleIcon.vue";
import LinkedInIcon from "./Icons/LinkedInIcon.vue";

defineProps<{
  providersConfig: {
    button_text: string;
    providers: { name: string; icon: string; style: string }[];
  };
}>();

const redirect = (provider: string) => {
  window.location.href = route("social.redirect", {
    provider,
  });
};
</script>

<template>
  <div class="flex gap-4 items-center">
    <div class="flex-1">
      <div class="w-full h-px bg-border" />
    </div>
    or
    <div class="flex-1">
      <div class="w-full h-px bg-border" />
    </div>
  </div>

  <div class="flex flex-col gap-4">
    <template
      v-for="provider in providersConfig.providers"
      :key="provider.name"
    >
      <Button
        type="button"
        variant="outline"
        :class="provider.style"
        tabIndex="{5}"
        @click="redirect(provider.name)"
      >
        <div v-if="provider.icon === 'GoogleIcon'">
          <GoogleIcon class="size-6" />
        </div>
        <div v-if="provider.icon === 'FacebookIcon'">
          <FacebookIcon class="size-6" />
        </div>
        <div v-if="provider.icon === 'GitHubIcon'">
          <GitHubIcon class="size-6" />
        </div>
        <div v-if="provider.icon === 'LinkedInIcon'">
          <LinkedInIcon class="size-6" />
        </div>
        {{ providersConfig.button_text.replace("{provider}", provider.name) }}
      </Button>
    </template>
  </div>
</template>

// stubs/react/components/socialite-plus.tsx
import FacebookIcon from "@/components/icons/facebook";
import GithubIcon from "@/components/icons/github";
import GoogleIcon from "@/components/icons/google";
import { Button } from "@/components/ui/button";
import LinkedInIcon from "./icons/linkedin";

interface SocialitePlusProps {
  providersConfig: {
    button_text: string;
    providers: { name: string; icon: string; style: string }[];
  };
}

export default function SocialitePlus({ providersConfig }: SocialitePlusProps) {
  return (
    <>
      <div className="flex gap-4 items-center">
        <div className="flex-1">
          <div className="w-full h-px bg-border" />
        </div>
        or
        <div className="flex-1">
          <div className="w-full h-px bg-border" />
        </div>
      </div>

      <div className="flex flex-col gap-4">
        {Object.values(providersConfig.providers).map((provider) => (
          <Button
            key={provider.name}
            type="button"
            variant="outline"
            className={`${provider.style}`}
            tabIndex={5}
            onClick={() => {
              window.location.href = route("social.redirect", {
                provider: provider.name,
              });
            }}
          >
            {provider.icon === "FacebookIcon" ? (
              <FacebookIcon className="size-6" />
            ) : provider.icon === "GithubIcon" ? (
              <GithubIcon className="size-6" />
            ) : provider.icon === "GoogleIcon" ? (
              <GoogleIcon className="size-6" />
            ) : provider.icon === "LinkedInIcon" ? (
              <LinkedInIcon className="size-6" />
            ) : null}
            {providersConfig.button_text.replace("{provider}", provider.name)}
          </Button>
        ))}
      </div>
    </>
  );
}
